# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Getter.KernelGetterService_pb2 as KernelGetterService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class GETTER_INFORMATIONStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UNAME = channel.unary_unary(
                '/GETTER_INFORMATION/UNAME',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=KernelGetterService__pb2.MODULE.FromString,
                )
        self.MODINFO = channel.unary_stream(
                '/GETTER_INFORMATION/MODINFO',
                request_serializer=KernelGetterService__pb2.MODULE.SerializeToString,
                response_deserializer=KernelGetterService__pb2.MODULE.FromString,
                )
        self.CURRENT_CONFIG = channel.unary_unary(
                '/GETTER_INFORMATION/CURRENT_CONFIG',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=KernelGetterService__pb2.MODULE.FromString,
                )
        self.RUNNING_MODULES = channel.unary_stream(
                '/GETTER_INFORMATION/RUNNING_MODULES',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=KernelGetterService__pb2.MODULE.FromString,
                )
        self.ALL_MODULES = channel.unary_stream(
                '/GETTER_INFORMATION/ALL_MODULES',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=KernelGetterService__pb2.MODULE.FromString,
                )
        self.ALL_USER_SPACE_OBJECTS = channel.unary_stream(
                '/GETTER_INFORMATION/ALL_USER_SPACE_OBJECTS',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=KernelGetterService__pb2.MODULE.FromString,
                )


class GETTER_INFORMATIONServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UNAME(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MODINFO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CURRENT_CONFIG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RUNNING_MODULES(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ALL_MODULES(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ALL_USER_SPACE_OBJECTS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GETTER_INFORMATIONServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UNAME': grpc.unary_unary_rpc_method_handler(
                    servicer.UNAME,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=KernelGetterService__pb2.MODULE.SerializeToString,
            ),
            'MODINFO': grpc.unary_stream_rpc_method_handler(
                    servicer.MODINFO,
                    request_deserializer=KernelGetterService__pb2.MODULE.FromString,
                    response_serializer=KernelGetterService__pb2.MODULE.SerializeToString,
            ),
            'CURRENT_CONFIG': grpc.unary_unary_rpc_method_handler(
                    servicer.CURRENT_CONFIG,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=KernelGetterService__pb2.MODULE.SerializeToString,
            ),
            'RUNNING_MODULES': grpc.unary_stream_rpc_method_handler(
                    servicer.RUNNING_MODULES,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=KernelGetterService__pb2.MODULE.SerializeToString,
            ),
            'ALL_MODULES': grpc.unary_stream_rpc_method_handler(
                    servicer.ALL_MODULES,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=KernelGetterService__pb2.MODULE.SerializeToString,
            ),
            'ALL_USER_SPACE_OBJECTS': grpc.unary_stream_rpc_method_handler(
                    servicer.ALL_USER_SPACE_OBJECTS,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=KernelGetterService__pb2.MODULE.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GETTER_INFORMATION', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GETTER_INFORMATION(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UNAME(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GETTER_INFORMATION/UNAME',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            KernelGetterService__pb2.MODULE.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MODINFO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GETTER_INFORMATION/MODINFO',
            KernelGetterService__pb2.MODULE.SerializeToString,
            KernelGetterService__pb2.MODULE.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CURRENT_CONFIG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GETTER_INFORMATION/CURRENT_CONFIG',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            KernelGetterService__pb2.MODULE.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RUNNING_MODULES(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GETTER_INFORMATION/RUNNING_MODULES',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            KernelGetterService__pb2.MODULE.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ALL_MODULES(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GETTER_INFORMATION/ALL_MODULES',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            KernelGetterService__pb2.MODULE.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ALL_USER_SPACE_OBJECTS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GETTER_INFORMATION/ALL_USER_SPACE_OBJECTS',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            KernelGetterService__pb2.MODULE.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
